# Generated by Django 6.0 on 2026-02-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0003_alter_category_id_alter_habit_id_alter_habitlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('icon_code', models.IntegerField(default=59534)),
                ('color_value', models.BigIntegerField(default=4282090230)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'insight_templates',
            },
        ),
        migrations.CreateModel(
            name='MotivationalQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('general', 'General'), ('streak', 'Streak Motivation'), ('comeback', 'Comeback Encouragement'), ('milestone', 'Milestone Celebration'), ('morning', 'Morning Motivation'), ('evening', 'Evening Reflection')], default='general', max_length=50)),
                ('times_shown', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'motivational_quotes',
                'ordering': ['-times_shown'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Mode'), ('light', 'Light Mode'), ('system', 'System Default')], default='dark', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=10)),
                ('date_format', models.CharField(choices=[('mdy', 'MM/DD/YYYY'), ('dmy', 'DD/MM/YYYY'), ('ymd', 'YYYY-MM-DD')], default='mdy', max_length=10)),
                ('week_starts_on', models.IntegerField(choices=[(0, 'Monday'), (6, 'Sunday')], default=0)),
                ('default_reminder_time', models.TimeField(blank=True, null=True)),
                ('default_habit_color', models.BigIntegerField(default=4284704497)),
                ('show_in_leaderboard', models.BooleanField(default=True)),
                ('profile_is_public', models.BooleanField(default=False)),
                ('smart_insights_enabled', models.BooleanField(default=True)),
                ('motivational_quotes_enabled', models.BooleanField(default=True)),
                ('gamification_enabled', models.BooleanField(default=True)),
                ('data_retention_days', models.IntegerField(default=365)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('best_time', 'Best Performance Time'), ('consistent_habit', 'Most Consistent Habit'), ('declining_habit', 'Declining Habit Alert'), ('streak_milestone', 'Streak Milestone'), ('improvement', 'Improvement Opportunity'), ('celebration', 'Achievement Celebration'), ('recommendation', 'Recommendation'), ('weekly_summary', 'Weekly Summary')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('icon_code', models.IntegerField(default=59534)),
                ('color_value', models.BigIntegerField(default=4282090230)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('is_actionable', models.BooleanField(default=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_insigh_user_id_8b04f9_idx'), models.Index(fields=['user', 'insight_type'], name='user_insigh_user_id_7a841b_idx')],
            },
        ),
    ]
