# Generated by Django 6.0 on 2026-02-28 07:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0005_habit_visibility_alter_habit_category_name_and_more'),
        ('social', '0005_encouragement_groupchallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeHabit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(blank=True, default='🎯', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', max_length=10)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text='List of weekday indices (0=Mon..6=Sun) for custom frequency.')),
                ('target_count', models.IntegerField(default=1, help_text='Number of times per day/period to complete this habit.')),
                ('privacy', models.CharField(choices=[('private', 'Private'), ('friends_only', 'Friends Only'), ('public', 'Public')], default='friends_only', max_length=15)),
                ('max_members', models.IntegerField(default=50)),
                ('icon_code', models.IntegerField(default=59516)),
                ('color_value', models.BigIntegerField(default=4283385573)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('member_count', models.IntegerField(default=1)),
                ('total_completions', models.IntegerField(default=0)),
                ('xp_per_completion', models.IntegerField(default=15, help_text='XP awarded to a member when they complete this habit.')),
                ('bonus_all_complete_xp', models.IntegerField(default=25, help_text='Bonus XP when ALL members complete on the same day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, help_text='Group this shared habit belongs to (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_habits', to='social.grouphabit')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_collaborative_habits', to=settings.AUTH_USER_MODEL)),
                ('source_habit', models.ForeignKey(blank=True, help_text='Original personal habit this was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_instances', to='habits.habit')),
            ],
            options={
                'db_table': 'gt_collaborative_habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('impersonation', 'Impersonation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_abuse_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_abuse_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='grow_together.collaborativehabit')),
            ],
            options={
                'db_table': 'gt_abuse_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeHabitMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('total_xp_earned', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='grow_together.collaborativehabit')),
                ('linked_habit', models.ForeignKey(blank=True, help_text="User's personal habit linked to track progress.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborative_links', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_collaborative_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborativeHabitProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('completion_count', models.IntegerField(default=0, help_text='How many times completed today (for multi-count habits).')),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='grow_together.collaborativehabit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='grow_together.collaborativehabitmember')),
                ('user', models.ForeignKey(help_text='Denormalized for fast per-user queries.', on_delete=django.db.models.deletion.CASCADE, related_name='collaborative_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_collaborative_progress',
                'ordering': ['-date', '-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(choices=[('group_streak_7', '7-Day Group Streak'), ('group_streak_30', '30-Day Group Streak'), ('all_complete_day', '100% Team Completion Day'), ('total_completions_100', '100 Total Completions'), ('total_completions_500', '500 Total Completions'), ('member_streak_30', 'Member 30-Day Streak'), ('consistency_30', '30-Day Consistency')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('xp_reward', models.IntegerField(default=50)),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('icon_code', models.IntegerField(default=59448)),
                ('badge_emoji', models.CharField(default='🏆', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achieved_by', models.ForeignKey(blank=True, help_text='The user who triggered the milestone (if individual).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gt_achieved_milestones', to=settings.AUTH_USER_MODEL)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='grow_together.collaborativehabit')),
            ],
            options={
                'db_table': 'gt_group_milestones',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Habit Created'), ('joined', 'Member Joined'), ('left', 'Member Left'), ('removed', 'Member Removed'), ('completed', 'Completed Habit'), ('streak_milestone', 'Streak Milestone'), ('group_milestone', 'Group Milestone'), ('reacted', 'Reacted to Progress'), ('commented', 'Commented on Progress'), ('invited', 'Invitation Sent'), ('invite_accepted', 'Invitation Accepted'), ('settings_changed', 'Settings Changed'), ('all_completed', 'All Members Completed')], max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context (streak count, milestone name, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='grow_together.collaborativehabit')),
                ('target_user', models.ForeignKey(blank=True, help_text='The user this action was performed on, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gt_targeted_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('message', models.CharField(blank=True, default='', help_text='Optional personal message from the inviter.', max_length=300)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-expire invites after this time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='grow_together.collaborativehabit')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_invites_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_habit_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_progress_comments', to=settings.AUTH_USER_MODEL)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grow_together.collaborativehabitprogress')),
            ],
            options={
                'db_table': 'gt_progress_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('fire', '🔥 Fire'), ('clap', '👏 Clap'), ('heart', '❤️ Heart'), ('celebrate', '🎉 Celebrate'), ('strong', '💪 Strong')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='grow_together.collaborativehabitprogress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_progress_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_progress_reactions',
            },
        ),
        migrations.CreateModel(
            name='WeeklyLeaderboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('rank', models.IntegerField()),
                ('completions', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='grow_together.collaborativehabit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gt_leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gt_weekly_leaderboard',
                'ordering': ['rank'],
            },
        ),
        migrations.AddIndex(
            model_name='collaborativehabit',
            index=models.Index(fields=['owner', '-created_at'], name='gt_collabor_owner_i_def3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabit',
            index=models.Index(fields=['privacy', 'is_active'], name='gt_collabor_privacy_a90966_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabit',
            index=models.Index(fields=['group', '-created_at'], name='gt_collabor_group_i_071590_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabitmember',
            index=models.Index(fields=['user', 'is_active'], name='gt_collabor_user_id_708503_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabitmember',
            index=models.Index(fields=['collaborative_habit', 'is_active', '-current_streak'], name='gt_collabor_collabo_4e69f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborativehabitmember',
            unique_together={('collaborative_habit', 'user')},
        ),
        migrations.AddIndex(
            model_name='collaborativehabitprogress',
            index=models.Index(fields=['collaborative_habit', 'date'], name='gt_collabor_collabo_5bc19a_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabitprogress',
            index=models.Index(fields=['user', 'date'], name='gt_collabor_user_id_57f9d2_idx'),
        ),
        migrations.AddIndex(
            model_name='collaborativehabitprogress',
            index=models.Index(fields=['collaborative_habit', 'date', 'completed'], name='gt_collabor_collabo_ebabee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaborativehabitprogress',
            unique_together={('member', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmilestone',
            unique_together={('collaborative_habit', 'milestone_type')},
        ),
        migrations.AddIndex(
            model_name='habitactivitylog',
            index=models.Index(fields=['collaborative_habit', '-created_at'], name='gt_activity_collabo_7ba6a0_idx'),
        ),
        migrations.AddIndex(
            model_name='habitactivitylog',
            index=models.Index(fields=['actor', '-created_at'], name='gt_activity_actor_i_130f57_idx'),
        ),
        migrations.AddIndex(
            model_name='habitinvite',
            index=models.Index(fields=['invited_user', 'status'], name='gt_habit_in_invited_10703c_idx'),
        ),
        migrations.AddIndex(
            model_name='habitinvite',
            index=models.Index(fields=['collaborative_habit', 'status'], name='gt_habit_in_collabo_786260_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitinvite',
            unique_together={('collaborative_habit', 'invited_user')},
        ),
        migrations.AddIndex(
            model_name='progresscomment',
            index=models.Index(fields=['progress', '-created_at'], name='gt_progress_progres_44d543_idx'),
        ),
        migrations.AddIndex(
            model_name='progressreaction',
            index=models.Index(fields=['progress', 'reaction_type'], name='gt_progress_progres_3d7cdd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressreaction',
            unique_together={('progress', 'user', 'reaction_type')},
        ),
        migrations.AddIndex(
            model_name='weeklyleaderboard',
            index=models.Index(fields=['collaborative_habit', 'week_start', 'rank'], name='gt_weekly_l_collabo_4fad0a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyleaderboard',
            unique_together={('collaborative_habit', 'user', 'week_start')},
        ),
    ]
