# Generated by Django 6.0 on 2026-03-01 02:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_together', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakFreeze',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], default='available', max_length=10)),
                ('source', models.CharField(choices=[('earned', 'Earned from streak milestone'), ('purchased', 'Purchased with XP'), ('gifted', 'Gifted by teammate'), ('bonus', 'Weekly bonus')], default='earned', max_length=10)),
                ('used_on_date', models.DateField(blank=True, help_text='The date this freeze was consumed to protect a streak.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry for this freeze token.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborative_habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freezes', to='grow_together.collaborativehabit')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freezes', to='grow_together.collaborativehabitmember')),
            ],
            options={
                'db_table': 'gt_streak_freezes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'status'], name='gt_streak_f_member__b858ea_idx'), models.Index(fields=['collaborative_habit', 'status'], name='gt_streak_f_collabo_fa719a_idx')],
            },
        ),
    ]
