# Generated by Django 6.0 on 2026-02-06 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_code', models.IntegerField(default=59516)),
                ('color_value', models.BigIntegerField(default=4284704497)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'habit_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed'), ('partial', 'Partial')], default='completed', max_length=20)),
                ('count', models.IntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('mood_rating', models.IntegerField(blank=True, null=True)),
                ('energy_level', models.IntegerField(blank=True, null=True)),
                ('partial_score', models.FloatField(default=1.0, help_text='Completion score: 1.0=full, 0.5=half, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-date', '-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('streak_start_date', models.DateField(blank=True, null=True)),
                ('total_completions', models.IntegerField(default=0)),
                ('total_skips', models.IntegerField(default=0)),
                ('total_misses', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habit_streaks',
            },
        ),
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='habit',
            name='category_name',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='habit',
            name='custom_days',
            field=models.JSONField(blank=True, default=list, help_text='List of weekday numbers (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='difficulty_score',
            field=models.IntegerField(default=3, help_text='1=Easy, 5=Very Hard — auto or user assigned'),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='Reason for pausing'),
        ),
        migrations.AddField(
            model_name='habit',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Manual sort position (lower = higher)'),
        ),
        migrations.AddField(
            model_name='habit',
            name='target_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color_value',
            field=models.BigIntegerField(default=4284704497, help_text='Flutter Color value (ARGB)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon_code',
            field=models.IntegerField(default=59516, help_text='Flutter Icon codePoint'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='habit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelTable(
            name='habit',
            table='habits',
        ),
        migrations.AlterModelTable(
            name='habitcompletion',
            table='habit_completions',
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='habits.category'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'status'], name='habits_user_id_4024f1_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_deleted'], name='habits_user_id_6ddbfe_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'created_at'], name='habits_user_id_1b4ff2_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['status', 'is_deleted'], name='habits_status_4be6a8_idx'),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='streak',
            name='habit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='habits.habit'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='habit_logs_habit_i_bab3fe_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['date', 'status'], name='habit_logs_date_ded4f4_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'status'], name='habit_logs_habit_i_a13090_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
    ]
