# Generated by Django 6.0 on 2026-02-07 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_category_id_alter_habit_id_alter_habitlog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
