# Generated by Django 6.0 on 2026-02-15 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('friends_only', 'Friends Only'), ('public', 'Public')], default='private', help_text='Controls who can see this habit: private, friends_only, or public.', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category_name',
            field=models.CharField(default='General', help_text='Denormalised category label used as fallback when FK is null.', max_length=100),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color_value',
            field=models.BigIntegerField(default=4284704497, help_text='Flutter Color value stored as ARGB integer'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='difficulty_score',
            field=models.IntegerField(default=3, help_text='Subjective difficulty: 1 = Easy … 5 = Very Hard'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='icon_code',
            field=models.IntegerField(default=59516, help_text='Flutter Icon codePoint (Material Icons)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='pause_reason',
            field=models.TextField(blank=True, help_text='User-supplied reason for pausing'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Manual sort position — lower values appear first'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_count',
            field=models.IntegerField(default=1, help_text='Number of times the habit should be done per scheduled day.'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='user',
            field=models.ForeignKey(help_text='Owner of this habit.', on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['visibility', 'is_deleted'], name='habits_visibil_7d4ea0_idx'),
        ),
    ]
