"""
Insights Models — DailyHabits Application
=========================================

Defines the data models for the smart insights and personalisation engine.
This module contains:

- **MotivationalQuote**: Curated collection of motivational quotes served to
  users on a rotating basis, with built-in usage tracking for fairness.
- **UserInsight**: Personalized, actionable insights generated by the analytics
  pipeline (e.g. best-time analysis, streak milestones, decline alerts).
- **InsightTemplate**: Configurable templates that drive automated insight
  generation, allowing non-developer staff to tune messaging.
- **UserPreferences**: Per-user settings covering display, privacy, feature
  flags, and default values.

All models use explicit `db_table` names and carry database-level indexes
where frequent query patterns benefit.
"""

# ===========================================================================
# Imports
# ===========================================================================

from django.db import models
from django.conf import settings


# ===========================================================================
# Model: MotivationalQuote
# ===========================================================================


class MotivationalQuote(models.Model):
    """
    Curated collection of motivational quotes delivered to users.

    Quotes are categorised (general, streak, comeback, etc.) so the insight
    engine can serve contextually relevant content.  A simple *least-shown*
    rotation algorithm ensures variety — see ``InsightService.get_daily_quote``.

    Attributes:
        quote (TextField): The full quote text.
        author (CharField): Attribution; blank when the author is unknown.
        category (CharField): One of the predefined ``CATEGORIES`` choices
            that determines when the quote is surfaced.
        times_shown (IntegerField): Counter incremented each time the quote
            is served, used by the rotation algorithm.
        is_active (BooleanField): Soft-disable flag — inactive quotes are
            excluded from selection.
        language (CharField): ISO-639-1 language code for future
            localisation support.
        created_at (DateTimeField): Timestamp of record creation.
    """

    # ------------------------------------------------------------------
    # Category choices — each maps to a contextual delivery scenario
    # ------------------------------------------------------------------
    CATEGORIES = [
        ('general', 'General'),
        ('streak', 'Streak Motivation'),
        ('comeback', 'Comeback Encouragement'),
        ('milestone', 'Milestone Celebration'),
        ('morning', 'Morning Motivation'),
        ('evening', 'Evening Reflection'),
    ]

    # ------------------------------------------------------------------
    # Core content fields
    # ------------------------------------------------------------------
    quote = models.TextField()
    author = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=50, choices=CATEGORIES, default='general')

    # ------------------------------------------------------------------
    # Usage tracking — drives the least-shown rotation algorithm
    # ------------------------------------------------------------------
    times_shown = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    # ------------------------------------------------------------------
    # Localization
    # ------------------------------------------------------------------
    language = models.CharField(max_length=10, default='en')

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'motivational_quotes'
        ordering = ['-times_shown']  # Most popular first by default

    def __str__(self):
        """Return a truncated preview of the quote with its author."""
        return f'"{self.quote[:50]}..." - {self.author}'


# ===========================================================================
# Model: UserInsight
# ===========================================================================


class UserInsight(models.Model):
    """
    Personalized, time-bound insight delivered to an individual user.

    Each record represents a single insight card shown on the dashboard.
    Insights are generated by ``InsightService`` and cover performance
    analysis, streak milestones, decline alerts, and recommendations.

    Lifecycle:
        1. Created by the insight engine with ``is_read=False``.
        2. Marked as read when the user views the card.
        3. Optionally dismissed or acted upon.
        4. Expired when ``valid_until`` is reached (nullable = no expiry).

    Attributes:
        user (FK → AUTH_USER_MODEL): Owner of this insight.
        insight_type (CharField): Categorises the insight for filtering
            and rendering (see ``INSIGHT_TYPES``).
        title (CharField): Short headline shown on the insight card.
        message (TextField): Detailed body copy with contextual advice.
        habit (FK → Habit): Optional link to the habit this insight
            relates to.
        data (JSONField): Arbitrary context payload (e.g. percentages,
            historical values) consumed by the front-end.
        priority (CharField): Determines sort order and visual emphasis.
        icon_code / color_value: Material-icon code point and ARGB colour
            for Flutter rendering.
        is_read / is_dismissed / is_actionable / action_taken: Lifecycle
            status flags.
        valid_from / valid_until: Window during which the insight is
            relevant.
        created_at (DateTimeField): Record creation timestamp.
    """

    # ------------------------------------------------------------------
    # Insight type choices — each maps to a distinct analytic scenario
    # ------------------------------------------------------------------
    INSIGHT_TYPES = [
        ('best_time', 'Best Performance Time'),
        ('consistent_habit', 'Most Consistent Habit'),
        ('declining_habit', 'Declining Habit Alert'),
        ('streak_milestone', 'Streak Milestone'),
        ('improvement', 'Improvement Opportunity'),
        ('celebration', 'Achievement Celebration'),
        ('recommendation', 'Recommendation'),
        ('weekly_summary', 'Weekly Summary'),
    ]

    # ------------------------------------------------------------------
    # Priority levels — affect card ordering and visual treatment
    # ------------------------------------------------------------------
    PRIORITY_LEVELS = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('urgent', 'Urgent'),
    ]

    # ------------------------------------------------------------------
    # Relationships
    # ------------------------------------------------------------------
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='insights'
    )

    # ------------------------------------------------------------------
    # Content fields
    # ------------------------------------------------------------------
    insight_type = models.CharField(max_length=50, choices=INSIGHT_TYPES)
    title = models.CharField(max_length=255)
    message = models.TextField()

    # ------------------------------------------------------------------
    # Related data — optional habit link and freeform context payload
    # ------------------------------------------------------------------
    habit = models.ForeignKey(
        'habits.Habit',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='insights'
    )
    data = models.JSONField(default=dict)  # Additional context data for the front-end

    # ------------------------------------------------------------------
    # Display — icon and colour are Material-icon code points / ARGB
    # ------------------------------------------------------------------
    priority = models.CharField(max_length=20, choices=PRIORITY_LEVELS, default='medium')
    icon_code = models.IntegerField(default=0xE88E)       # Material icon code point
    color_value = models.BigIntegerField(default=0xFF3B82F6)  # ARGB colour value

    # ------------------------------------------------------------------
    # Lifecycle status flags
    # ------------------------------------------------------------------
    is_read = models.BooleanField(default=False)
    is_dismissed = models.BooleanField(default=False)
    is_actionable = models.BooleanField(default=True)
    action_taken = models.BooleanField(default=False)

    # ------------------------------------------------------------------
    # Validity window — null `valid_until` means the insight never expires
    # ------------------------------------------------------------------
    valid_from = models.DateTimeField(auto_now_add=True)
    valid_until = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user_insights'
        ordering = ['-created_at']  # Newest insights first
        indexes = [
            # Optimise the "unread insights for user" dashboard query
            models.Index(fields=['user', 'is_read']),
            # Optimise filtering by insight type per user
            models.Index(fields=['user', 'insight_type']),
        ]

    def __str__(self):
        """Return the insight title paired with the owning user's email."""
        return f"{self.title} - {self.user.email}"


# ===========================================================================
# Model: InsightTemplate
# ===========================================================================


class InsightTemplate(models.Model):
    """
    Configurable template for automated insight generation.

    Staff members can create and edit templates via the Django admin to
    control the messaging users receive without code changes.  Each
    template is keyed by a unique ``insight_type`` and contains Python
    ``.format()``-compatible placeholders in both title and message.

    ``trigger_conditions`` stores a JSON object that the insight engine
    evaluates to decide whether to instantiate this template for a user
    (e.g. ``{"min_streak": 7, "min_consistency": 80}``).

    Attributes:
        insight_type (CharField): Unique key tying the template to a
            specific analytic scenario.
        title_template (CharField): Title with ``{placeholder}`` tokens.
        message_template (TextField): Body text with ``{placeholder}``
            tokens.
        trigger_conditions (JSONField): Dict of conditions the engine
            checks before generating this insight.
        icon_code / color_value: Default visual properties copied to the
            generated ``UserInsight``.
        is_active (BooleanField): Soft-disable toggle.
        created_at / updated_at: Audit timestamps.
    """

    # ------------------------------------------------------------------
    # Template identification & content
    # ------------------------------------------------------------------
    insight_type = models.CharField(max_length=50, unique=True)
    title_template = models.CharField(max_length=255)
    message_template = models.TextField()

    # ------------------------------------------------------------------
    # Trigger conditions — evaluated by the insight engine at runtime
    # ------------------------------------------------------------------
    trigger_conditions = models.JSONField(default=dict)

    # ------------------------------------------------------------------
    # Visual defaults — copied onto each generated UserInsight
    # ------------------------------------------------------------------
    icon_code = models.IntegerField(default=0xE88E)
    color_value = models.BigIntegerField(default=0xFF3B82F6)

    is_active = models.BooleanField(default=True)

    # ------------------------------------------------------------------
    # Audit timestamps
    # ------------------------------------------------------------------
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'insight_templates'

    def __str__(self):
        """Return a descriptive label including the insight type key."""
        return f"Template: {self.insight_type}"


# ===========================================================================
# Model: UserPreferences
# ===========================================================================


class UserPreferences(models.Model):
    """
    Per-user settings and personalisation preferences.

    A ``UserPreferences`` record is created automatically for every new
    user (see the ``authentication`` app's post-save signal).  It holds
    display customisation, privacy flags, feature toggles, and default
    values that are consumed by both the Django backend and the Flutter
    front-end.

    Attributes:
        user (OneToOneField → AUTH_USER_MODEL): Owning user.
        theme (CharField): UI theme preference (dark / light / system).
        language (CharField): Preferred display language.
        date_format (CharField): Date rendering format.
        week_starts_on (IntegerField): ``0`` = Monday, ``6`` = Sunday.
        default_reminder_time (TimeField): Pre-filled reminder time for
            newly created habits (nullable).
        default_habit_color (BigIntegerField): Pre-filled ARGB colour
            for new habits.
        show_in_leaderboard (BooleanField): Whether the user appears in
            the social leaderboard.
        profile_is_public (BooleanField): Whether the profile is
            visible to other users.
        smart_insights_enabled (BooleanField): Toggle the insight engine.
        motivational_quotes_enabled (BooleanField): Toggle quote cards.
        gamification_enabled (BooleanField): Toggle achievements and XP.
        data_retention_days (IntegerField): How long historical data is
            kept before automatic purging.
        updated_at (DateTimeField): Last modification timestamp.
    """

    # ------------------------------------------------------------------
    # Language choices — extend here when adding new locales
    # ------------------------------------------------------------------
    LANGUAGE_CHOICES = [
        ('en', 'English'),
        ('ne', 'Nepali'),
    ]

    # ------------------------------------------------------------------
    # Theme choices — consumed by the Flutter ThemeData builder
    # ------------------------------------------------------------------
    THEME_CHOICES = [
        ('dark', 'Dark Mode'),
        ('light', 'Light Mode'),
        ('system', 'System Default'),
    ]

    # ------------------------------------------------------------------
    # Date-format choices — applied in both backend serialisation and
    # Flutter date widgets
    # ------------------------------------------------------------------
    DATE_FORMAT_CHOICES = [
        ('mdy', 'MM/DD/YYYY'),
        ('dmy', 'DD/MM/YYYY'),
        ('ymd', 'YYYY-MM-DD'),
    ]

    # ------------------------------------------------------------------
    # Week-start choices — 0 = Monday (ISO), 6 = Sunday (US convention)
    # ------------------------------------------------------------------
    WEEK_START_CHOICES = [
        (0, 'Monday'),
        (6, 'Sunday'),
    ]

    # ------------------------------------------------------------------
    # One-to-one relationship with the user
    # ------------------------------------------------------------------
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='preferences'
    )

    # ------------------------------------------------------------------
    # Display & localisation settings
    # ------------------------------------------------------------------
    theme = models.CharField(max_length=20, choices=THEME_CHOICES, default='dark')
    language = models.CharField(max_length=10, choices=LANGUAGE_CHOICES, default='en')
    date_format = models.CharField(max_length=10, choices=DATE_FORMAT_CHOICES, default='mdy')
    week_starts_on = models.IntegerField(choices=WEEK_START_CHOICES, default=0)

    # ------------------------------------------------------------------
    # Habit defaults — pre-filled when the user creates a new habit
    # ------------------------------------------------------------------
    default_reminder_time = models.TimeField(null=True, blank=True)
    default_habit_color = models.BigIntegerField(default=0xFF6366F1)  # Indigo ARGB

    # ------------------------------------------------------------------
    # Privacy controls
    # ------------------------------------------------------------------
    show_in_leaderboard = models.BooleanField(default=True)
    profile_is_public = models.BooleanField(default=False)

    # ------------------------------------------------------------------
    # Feature toggles — allow users to opt in/out of major features
    # ------------------------------------------------------------------
    smart_insights_enabled = models.BooleanField(default=True)
    motivational_quotes_enabled = models.BooleanField(default=True)
    gamification_enabled = models.BooleanField(default=True)

    # ------------------------------------------------------------------
    # Data retention policy
    # ------------------------------------------------------------------
    data_retention_days = models.IntegerField(default=365)  # Days before auto-purge

    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'user_preferences'

    def __str__(self):
        return f"Preferences - {self.user.email}"
