# Generated by Django 6.0 on 2026-02-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0003_alter_category_id_alter_habit_id_alter_habitlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_completions', models.IntegerField(default=0)),
                ('total_days_tracked', models.IntegerField(default=0)),
                ('lifetime_completion_rate', models.FloatField(default=0.0)),
                ('last_7_days_rate', models.FloatField(default=0.0)),
                ('last_30_days_rate', models.FloatField(default=0.0)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('trend_percentage', models.FloatField(default=0.0)),
                ('best_streak_ever', models.IntegerField(default=0)),
                ('best_month', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='habits.habit')),
            ],
            options={
                'db_table': 'analytics_habit_analytics',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_habits', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('missed_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('consistency_rate', models.FloatField(default=0.0)),
                ('current_overall_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_daily_summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='analytics_d_user_id_0564af_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_completions', models.IntegerField(default=0)),
                ('total_habits_tracked', models.IntegerField(default=0)),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('best_week', models.IntegerField(blank=True, null=True)),
                ('heatmap_data', models.JSONField(default=list)),
                ('category_stats', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_monthly_summaries',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('year', models.IntegerField()),
                ('week_number', models.IntegerField()),
                ('total_completions', models.IntegerField(default=0)),
                ('total_habits_tracked', models.IntegerField(default=0)),
                ('average_completion_rate', models.FloatField(default=0.0)),
                ('best_day', models.CharField(blank=True, max_length=20)),
                ('worst_day', models.CharField(blank=True, max_length=20)),
                ('daily_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_weekly_summaries',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'year', 'week_number')},
            },
        ),
    ]
