# Generated by Django 6.0 on 2026-02-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        ('habits', '0003_alter_category_id_alter_habit_id_alter_habitlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitReminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reminder_time', models.TimeField()),
                ('repeat_type', models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom Days')], default='daily', max_length=20)),
                ('custom_days', models.JSONField(default=list)),
                ('is_enabled', models.BooleanField(default=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('habit_reminders', models.BooleanField(default=True)),
                ('missed_habit_alerts', models.BooleanField(default=True)),
                ('achievement_notifications', models.BooleanField(default=True)),
                ('streak_alerts', models.BooleanField(default=True)),
                ('insight_notifications', models.BooleanField(default=True)),
                ('motivational_quotes', models.BooleanField(default=True)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('reminder_minutes_before', models.IntegerField(default=15)),
                ('max_notifications_per_day', models.IntegerField(default=20)),
                ('default_snooze_minutes', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('reminder', 'Habit Reminder'), ('missed', 'Missed Habit Alert'), ('achievement', 'Achievement Earned'), ('streak', 'Streak Alert'), ('insight', 'Smart Insight'), ('motivation', 'Motivational'), ('level_up', 'Level Up'), ('system', 'System Notification')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('scheduled_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed')], default='pending', max_length=20)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('action_data', models.JSONField(default=dict)),
                ('icon_code', models.IntegerField(default=59380)),
                ('color_value', models.BigIntegerField(default=4284704497)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-scheduled_time'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_8ab96f_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_63f199_idx'), models.Index(fields=['scheduled_time', 'status'], name='notificatio_schedul_b2630e_idx')],
            },
        ),
    ]
