# Generated by Django 6.0 on 2026-02-07 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('habits', '0004_alter_habit_start_date'),
        ('notifications', '0001_initial'),
        ('social', '0003_feedpost_friendship_postcomment_postlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartTip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tip_type', models.CharField(choices=[('missed_habit', 'Missed Habit Encouragement'), ('streak_close', 'Near Streak Milestone'), ('declining', 'Declining Consistency'), ('time_pattern', 'Time-based Pattern'), ('category_tip', 'Category-based Tip'), ('preference', 'User Preference Tip'), ('weekly', 'Weekly Insight'), ('general', 'General Wellness Tip')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon_code', models.IntegerField(default=59534)),
                ('color_value', models.BigIntegerField(default=4279548070)),
                ('is_read', models.BooleanField(default=False)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'smart_tips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_schedul_b2630e_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('habit_detail', 'Open Habit Detail'), ('community', 'Open Community'), ('group_detail', 'Open Group Detail'), ('profile', 'Open Profile'), ('friend_requests', 'Open Friend Requests'), ('achievements', 'Open Achievements'), ('settings', 'Open Settings')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='social.grouphabit'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='smart_tips_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='social_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Habit Reminder'), ('missed', 'Missed Habit Alert'), ('achievement', 'Achievement Earned'), ('streak', 'Streak Milestone'), ('level_up', 'Level Up'), ('system', 'System Notification'), ('admin', 'Admin Announcement'), ('security', 'Security Alert'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('group_join', 'Group Join'), ('group_approval', 'Group Approval'), ('group_challenge', 'Group Challenge Update'), ('social_like', 'Post Liked'), ('social_comment', 'Post Comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('dismissed', 'Dismissed'), ('snoozed', 'Snoozed')], default='sent', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_a34568_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'),
        ),
        migrations.AddField(
            model_name='smarttip',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smart_tips', to='habits.habit'),
        ),
        migrations.AddField(
            model_name='smarttip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_tips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='smarttip',
            index=models.Index(fields=['user', 'is_read'], name='smart_tips_user_id_d95173_idx'),
        ),
        migrations.AddIndex(
            model_name='smarttip',
            index=models.Index(fields=['user', 'is_dismissed'], name='smart_tips_user_id_46d873_idx'),
        ),
        migrations.AddIndex(
            model_name='smarttip',
            index=models.Index(fields=['user', '-created_at'], name='smart_tips_user_id_37db2b_idx'),
        ),
    ]
