# Generated by Django 6.0 on 2026-03-12 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_smarttip_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.CharField(choices=[('none', 'No Action'), ('habit_detail', 'Open Habit Detail'), ('community', 'Open Community'), ('group_detail', 'Open Group Detail'), ('profile', 'Open Profile'), ('friend_requests', 'Open Friend Requests'), ('achievements', 'Open Achievements'), ('settings', 'Open Settings'), ('challenge_detail', 'Open Challenge'), ('leaderboard', 'Open Leaderboard')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Habit Reminder'), ('missed', 'Missed Habit Alert'), ('achievement', 'Achievement Earned'), ('streak', 'Streak Milestone'), ('streak_risk', 'Streak At Risk'), ('level_up', 'Level Up'), ('system', 'System Notification'), ('admin', 'Admin Announcement'), ('security', 'Security Alert'), ('challenge', 'Challenge Update'), ('challenge_joined', 'Challenge Joined'), ('challenge_ending', 'Challenge Ending Soon'), ('challenge_completed', 'Challenge Completed'), ('leaderboard', 'Leaderboard Update'), ('friend_request', 'Friend Request'), ('friend_accepted', 'Friend Request Accepted'), ('group_join', 'Group Join'), ('group_approval', 'Group Approval'), ('group_challenge', 'Group Challenge Update'), ('social_like', 'Post Liked'), ('social_comment', 'Post Comment')], max_length=50),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'device_tokens',
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_toke_user_id_e99165_idx')],
            },
        ),
    ]
