# Generated by Django 6.0 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='cooldown_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='delivery_mode',
            field=models.CharField(choices=[('instant', 'Instant'), ('digest', 'Digest')], default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='digest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='reminder_window_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='reminder_window_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='weekend_reminders_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
