# Generated by Django 6.0 on 2026-02-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_datadeletionrequest_loginactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadeletionrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loginactivity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
