# Generated by Django 6.0 on 2026-02-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_datadeletionrequest_id_alter_loginactivity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('request', 'Reset Requested'), ('email_sent', 'Email Sent'), ('token_validated', 'Token Validated'), ('password_changed', 'Password Changed'), ('token_expired', 'Token Expired'), ('token_invalid', 'Invalid Token Attempt'), ('rate_limited', 'Rate Limited'), ('suspicious', 'Suspicious Activity')], max_length=20)),
                ('email', models.EmailField(help_text='Email address used in the request.', max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload with event-specific details.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the raw reset token.', max_length=128, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='idx_prt_token_hash'), models.Index(fields=['user', 'is_used'], name='idx_prt_user_used')],
            },
        ),
    ]
