# Generated by Django 6.0 on 2026-03-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_passwordresetauditlog_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', help_text='How the user originally registered.', max_length=20, verbose_name='Primary Auth Provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, db_index=True, help_text='Google OAuth `sub` claim — unique, stable identifier.', max_length=255, null=True, unique=True, verbose_name='Google Subject ID'),
        ),
    ]
