# Generated by Django 6.0 on 2026-03-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_google_id_and_auth_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetauditlog',
            name='event',
            field=models.CharField(choices=[('request', 'Reset Requested'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Delivery Failed'), ('token_validated', 'Token Validated'), ('password_changed', 'Password Changed'), ('token_expired', 'Token Expired'), ('token_invalid', 'Invalid Token Attempt'), ('rate_limited', 'Rate Limited'), ('suspicious', 'Suspicious Activity')], max_length=20),
        ),
    ]
