# Generated by Django 6.0 on 2026-03-01 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_email_failed_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetauditlog',
            name='event',
            field=models.CharField(choices=[('request', 'Reset Requested'), ('otp_request', 'OTP Requested'), ('otp_sent', 'OTP Email Sent'), ('otp_failed', 'OTP Email Failed'), ('otp_verified', 'OTP Verified'), ('otp_invalid', 'Invalid OTP Attempt'), ('otp_expired', 'OTP Expired'), ('otp_locked', 'OTP Locked (Max Attempts)'), ('email_sent', 'Email Sent'), ('email_failed', 'Email Delivery Failed'), ('token_validated', 'Token Validated'), ('password_changed', 'Password Changed'), ('token_expired', 'Token Expired'), ('token_invalid', 'Invalid Token Attempt'), ('rate_limited', 'Rate Limited'), ('suspicious', 'Suspicious Activity')], max_length=20),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the 6-digit OTP.', max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of failed verification attempts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_reset_otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used'], name='idx_pro_user_used'), models.Index(fields=['expires_at'], name='idx_pro_expires')],
            },
        ),
    ]
