# Generated by Django 6.0 on 2026-02-07 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0003_alter_category_id_alter_habit_id_alter_habitlog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('streak', 'Streak Based'), ('completion', 'Completion Count'), ('consistency', 'Consistency Rate'), ('milestone', 'Milestone'), ('special', 'Special Achievement')], max_length=50)),
                ('target_value', models.IntegerField()),
                ('target_type', models.CharField(default='count', max_length=50)),
                ('icon_code', models.IntegerField(default=59515)),
                ('color_value', models.BigIntegerField(default=4294956800)),
                ('badge_image_url', models.URLField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('level_required', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['order', 'level_required', 'points'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('theme', 'Theme Unlock'), ('icon', 'Icon Pack'), ('badge', 'Special Badge'), ('feature', 'Feature Unlock')], max_length=50)),
                ('level_required', models.IntegerField(default=1)),
                ('points_required', models.IntegerField(default=0)),
                ('icon_code', models.IntegerField(default=59636)),
                ('preview_image_url', models.URLField(blank=True, null=True)),
                ('reward_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='achievements.achievement')),
            ],
            options={
                'db_table': 'rewards',
                'ordering': ['level_required', 'points_required'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.IntegerField(default=1)),
                ('current_xp', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('total_achievements', models.IntegerField(default=0)),
                ('achievements_this_month', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_levels',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('earned_value', models.IntegerField(default=0)),
                ('is_notified', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='achievements.achievement')),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement', 'habit')},
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rewards', to='achievements.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_rewards',
                'unique_together': {('user', 'reward')},
            },
        ),
    ]
