# Generated by Django 6.0 on 2026-02-22 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('friend', 'Friend Challenge'), ('community', 'Community')], default='personal', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='upcoming', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], default='medium', max_length=20)),
                ('criteria', models.JSONField(default=dict)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('xp_reward', models.IntegerField(default=100)),
                ('coin_reward', models.IntegerField(default=25)),
                ('max_participants', models.IntegerField(default=1)),
                ('invite_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('icon_code', models.IntegerField(default=59516)),
                ('color_value', models.BigIntegerField(default=4283385573)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge_reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='achievements.achievement')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='gamification.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenge_participants',
                'ordering': ['-progress_percentage'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'currency_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_bonus_claimed', models.BooleanField(default=False)),
                ('all_done_bonus_claimed', models.BooleanField(default=False)),
                ('xp_earned', models.IntegerField(default=0)),
                ('coins_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_bonuses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('alltime', 'All Time')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('score', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('consistency_pct', models.FloatField(default=0.0)),
                ('rank', models.IntegerField(default=0)),
                ('rank_change', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard_entries',
                'ordering': ['board_type', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_type', models.CharField(choices=[('level_up', 'Level Up'), ('streak', 'Streak Milestone'), ('completions', 'Completion Milestone'), ('days_active', 'Days Active')], max_length=30)),
                ('threshold', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('xp_reward', models.IntegerField(default=0)),
                ('coin_reward', models.IntegerField(default=0)),
                ('streak_freeze_reward', models.IntegerField(default=0)),
                ('icon_code', models.IntegerField(default=59448)),
                ('color_value', models.BigIntegerField(default=4294956800)),
                ('celebration_type', models.CharField(default='confetti', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'milestone_rewards',
                'ordering': ['milestone_type', 'threshold'],
                'unique_together': {('milestone_type', 'threshold')},
            },
        ),
        migrations.CreateModel(
            name='StreakFreeze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('used', 'Used'), ('expired', 'Expired')], default='available', max_length=20)),
                ('cost_coins', models.IntegerField(default=50)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('protected_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streak_freezes',
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('total_earned', models.IntegerField(default=0)),
                ('total_spent', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_currency',
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('source_type', models.CharField(choices=[('habit_completion', 'Habit Completion'), ('streak_bonus', 'Streak Bonus'), ('daily_all_done', 'All Habits Completed'), ('weekly_bonus', 'Weekly Consistency Bonus'), ('achievement', 'Achievement Earned'), ('challenge', 'Challenge Completed'), ('level_up_bonus', 'Level Up Bonus'), ('daily_login', 'Daily Login'), ('referral', 'Referral Bonus')], max_length=50)),
                ('source_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('multiplier', models.FloatField(default=1.0)),
                ('base_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'xp_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['scope', 'status'], name='challenges_scope_b6b8f7_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['status', 'end_date'], name='challenges_status_291ba5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipant',
            unique_together={('challenge', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='dailybonus',
            unique_together={('user', 'date')},
        ),
        migrations.AddIndex(
            model_name='leaderboardentry',
            index=models.Index(fields=['board_type', 'period_start', 'rank'], name='leaderboard_board_t_2112dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('user', 'board_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'source_type'], name='xp_events_user_id_9b9eba_idx'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', 'created_at'], name='xp_events_user_id_be9667_idx'),
        ),
    ]
