# Generated by Django 6.0 on 2026-02-06 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0002_category_habitlog_streak_alter_habit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('habit_template', models.JSONField(default=dict, help_text='Template data for creating the habit for each member')),
                ('invite_code', models.CharField(max_length=8, unique=True)),
                ('max_members', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_code', models.IntegerField(default=59387)),
                ('color_value', models.BigIntegerField(default=4293968782)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referral_links',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('referral_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='social.referrallink')),
            ],
            options={
                'db_table': 'referrals',
            },
        ),
        migrations.CreateModel(
            name='ShareCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Summary'), ('streak', 'Streak Milestone'), ('achievement', 'Achievement Earned'), ('custom', 'Custom Share')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('card_data', models.JSONField(default=dict, help_text='Structured data for rendering the share card')),
                ('habits_completed', models.IntegerField(default=0)),
                ('total_habits', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('share_url', models.URLField(blank=True)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('color_primary', models.CharField(default='#312C51', max_length=10)),
                ('color_accent', models.CharField(default='#F0C38E', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.grouphabit')),
                ('habit', models.ForeignKey(blank=True, help_text="The user's personal habit linked to this group", null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SharingPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_in_summary', models.BooleanField(default=True, help_text='Include in daily/weekly share cards')),
                ('allow_streak_share', models.BooleanField(default=True, help_text='Include streak milestones')),
                ('allow_in_group', models.BooleanField(default=True, help_text='Visible in group habits')),
                ('show_details', models.BooleanField(default=False, help_text='Show habit description/notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sharing_privacy',
                'unique_together': {('user', 'habit')},
            },
        ),
    ]
