# Generated by Django 6.0 on 2026-02-15 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_visibility_alter_habit_category_name_and_more'),
        ('social', '0003_feedpost_friendship_postcomment_postlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text (max 300 characters).', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_habit_comments', to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_comments', to='habits.habit')),
            ],
            options={
                'db_table': 'habit_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['habit', '-created_at'], name='habit_comme_habit_i_54f7f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='HabitReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍 Like'), ('encourage', '💪 Encourage'), ('celebrate', '🎉 Celebrate'), ('fire', '🔥 Fire'), ('clap', '👏 Clap')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_reactions',
                'indexes': [models.Index(fields=['habit', 'reaction_type'], name='habit_react_habit_i_fe2ad6_idx')],
                'unique_together': {('habit', 'user', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='SharedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_comment', models.BooleanField(default=True, help_text='Whether the recipient can comment on this habit.')),
                ('can_react', models.BooleanField(default=True, help_text='Whether the recipient can react to this habit.')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(help_text='The habit being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='habits.habit')),
                ('shared_by', models.ForeignKey(help_text='User who shared the habit (must be the habit owner).', on_delete=django.db.models.deletion.CASCADE, related_name='habits_shared_out', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(help_text='Friend who was granted access to view this habit.', on_delete=django.db.models.deletion.CASCADE, related_name='habits_shared_in', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shared_habits',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['shared_with', '-shared_at'], name='shared_habi_shared__a1a544_idx'), models.Index(fields=['habit', 'shared_by'], name='shared_habi_habit_i_29fd00_idx')],
                'unique_together': {('habit', 'shared_with')},
            },
        ),
    ]
