# Generated by Django 6.0 on 2026-02-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_visibility_alter_habit_category_name_and_more'),
        ('social', '0004_habitcomment_habitreaction_sharedhabit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encouragement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encourage_type', models.CharField(choices=[('cheer', '🎉 Cheer'), ('motivate', '💪 Motivate'), ('celebrate', '🏆 Celebrate'), ('remind', '⏰ Gentle Reminder')], default='cheer', max_length=20)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements_sent', to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encouragements', to='habits.habit')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'encouragements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChallenge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('completions', 'Total Completions'), ('streak', 'Streak Days'), ('all_done', 'All-Done Days')], default='completions', max_length=30)),
                ('target_value', models.IntegerField(default=50)),
                ('current_progress', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('xp_reward', models.IntegerField(default=50)),
                ('coin_reward', models.IntegerField(default=10)),
                ('icon_code', models.IntegerField(default=59448)),
                ('color_value', models.BigIntegerField(default=4294286859)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_group_challenges', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='social.grouphabit')),
            ],
            options={
                'db_table': 'group_challenges',
                'ordering': ['-created_at'],
            },
        ),
    ]
