# Generated by Django 6.0 on 2026-02-28 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='ai_personalization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='analytics_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_archive_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='default_habit_visibility',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='haptic_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='week_start_day',
            field=models.CharField(default='monday', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='accent_color',
            field=models.CharField(default='indigo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='daily_summary_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='quote_frequency',
            field=models.CharField(default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='quote_tone',
            field=models.CharField(default='calm', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(default='system', max_length=20),
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('device_name', models.CharField(default='Unknown Device', max_length=255)),
                ('device_type', models.CharField(default='unknown', max_length=50)),
                ('platform', models.CharField(default='unknown', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_current', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
                ('logged_in_at', models.DateTimeField(auto_now_add=True)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'login_sessions',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', max_length=20)),
                ('show_profile_in_search', models.BooleanField(default=True)),
                ('show_in_leaderboard', models.BooleanField(default=True)),
                ('who_can_view_habits', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', max_length=20)),
                ('who_can_view_streaks', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends Only'), ('private', 'Private')], default='friends', max_length=20)),
                ('share_progress_with_groups', models.BooleanField(default=True)),
                ('who_can_send_friend_requests', models.CharField(choices=[('everyone', 'Everyone'), ('friends_of_friends', 'Friends of Friends'), ('nobody', 'Nobody')], default='everyone', max_length=25)),
                ('allow_group_invites', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=False)),
                ('share_anonymous_usage_data', models.BooleanField(default=True)),
                ('allow_ai_training', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_method', models.CharField(default='email', max_length=20)),
                ('biometric_lock_enabled', models.BooleanField(default=False)),
                ('require_auth_for_export', models.BooleanField(default=True)),
                ('require_auth_for_delete', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.IntegerField(default=0)),
                ('login_notification_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_settings',
            },
        ),
        migrations.CreateModel(
            name='SettingsAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('profile', 'Profile Change'), ('appearance', 'Appearance Change'), ('notification', 'Notification Change'), ('privacy', 'Privacy Change'), ('security', 'Security Change'), ('export', 'Data Export'), ('account', 'Account Action')], max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.JSONField(default=dict)),
                ('new_value', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DeviceToken',
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['user', 'is_active'], name='login_sessi_user_id_f258eb_idx'),
        ),
        migrations.AddIndex(
            model_name='loginsession',
            index=models.Index(fields=['session_key'], name='login_sessi_session_9d336d_idx'),
        ),
        migrations.AddIndex(
            model_name='settingsauditlog',
            index=models.Index(fields=['user', 'category'], name='settings_au_user_id_8d7213_idx'),
        ),
        migrations.AddIndex(
            model_name='settingsauditlog',
            index=models.Index(fields=['user', '-created_at'], name='settings_au_user_id_f5bd2e_idx'),
        ),
    ]
